add modal
js-tasks-ru/htmlcss-20230530_valeria-vol pull request #10
Opened 2023-06-25 12:38 UTC by valeriarykova

2023-06-25 12:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-25 19:47 UTC, GSemikozov requested changes

2023-06-25 19:47 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  background-color: #C4C4C4;
лучше через rgba

2023-07-12 10:06 UTC, valeriarykova commented on 05-lection3/02-modal/modal.css
> +  background-color: #C4C4C4;
поправила

2023-07-12 14:02 UTC, GSemikozov approved these changes

2023-07-12 14:02 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-07-12 14:41 UTC, GSemikozov approved these changes

2023-07-12 14:41 UTC, merged