add input
js-tasks-ru/htmlcss-20230530_valeria-vol pull request #17
Opened 2023-07-12 11:45 UTC by valeriarykova

2023-07-12 11:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-12 12:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-12 13:48 UTC, GSemikozov requested changes

2023-07-12 13:48 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +      <svg width="350" height="56" viewBox="0 0 350 56" fill="none" class="form__icon">
что-то с иконками не то, ширина не должна быть 350px))
и лучше сложить в спрайт и импортировать оттуда.

2023-07-12 13:48 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  min-height: 56px;
лишнее

2023-07-12 13:48 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  min-height: 56px;
просто height

2023-07-12 13:48 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  padding-left: 24px;
справа тоже надо, с учетом ширины и расположения иконки

2023-07-12 13:48 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +  top: 18px;
иконка точно по середине будет?

2023-07-12 17:13 UTC, valeriarykova commented on 07-lection5/04-input/index.html
> +      <svg width="350" height="56" viewBox="0 0 350 56" fill="none" class="form__icon">
поправила

2023-07-12 17:13 UTC, valeriarykova commented on 07-lection5/04-input/input.css
> +  min-height: 56px;
удалила

2023-07-12 17:13 UTC, valeriarykova commented on 07-lection5/04-input/input.css
> +  min-height: 56px;
готово

2023-07-12 17:13 UTC, valeriarykova commented on 07-lection5/04-input/input.css
> +  padding-left: 24px;
поправила

2023-07-12 17:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-12 17:13 UTC, valeriarykova commented on 07-lection5/04-input/input.css
> +  top: 18px;
поправила

2023-07-12 17:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-02 12:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-02 12:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-02 12:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-08-05 20:57 UTC, GSemikozov approved these changes

2023-08-05 20:57 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-08-05 21:02 UTC, GSemikozov approved these changes

2023-08-05 21:02 UTC, merged