add layout
js-tasks-ru/htmlcss-20230530_valeria-vol pull request #5
Opened 2023-06-14 05:46 UTC by valeriarykova

2023-06-14 05:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-15 14:22 UTC, GSemikozov requested changes

2023-06-15 14:22 UTC, GSemikozov commented on components/footer/footer.css
> +  min-height: 383px;
лишнее ограничение

2023-06-15 14:22 UTC, GSemikozov commented on components/preveiw/preview.css
> +  justify-content: space-between;
лишнее)

2023-06-15 18:58 UTC, valeriarykova commented on components/preveiw/preview.css
> +  justify-content: space-between;
все поправила)

2023-07-12 13:54 UTC, GSemikozov approved these changes

2023-07-12 13:54 UTC, merged