add histogram
js-tasks-ru/htmlcss-20230530_valeria-vol pull request #6
Opened 2023-06-15 16:55 UTC by valeriarykova

2023-06-15 16:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-15 18:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-15 19:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-15 20:05 UTC, GSemikozov requested changes

2023-06-15 20:05 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  justify-content: space-between;
лишнее (нам достаточно gap)

2023-06-16 09:28 UTC, valeriarykova commented on 04-lection2/01-histogram/histogram.css
> +  justify-content: space-between;
поправила

2023-07-12 14:01 UTC, GSemikozov approved these changes

2023-07-12 14:01 UTC, merged