add skeleton
js-tasks-ru/htmlcss-20230530_valeria-vol pull request #7
Opened 2023-06-15 20:55 UTC by valeriarykova

2023-06-15 20:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-16 09:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-16 20:47 UTC, GSemikozov requested changes

2023-06-16 20:47 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 579px;
высоту и ширину удалим

2023-06-18 11:03 UTC, valeriarykova commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 579px;
готово

2023-06-18 11:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-12 14:01 UTC, GSemikozov submitted a review, later dismissed
все ок, но - конфликты

2023-07-12 14:01 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2023-08-05 20:57 UTC, GSemikozov approved these changes

2023-08-05 20:57 UTC, merged