add calendar
js-tasks-ru/htmlcss-20230530_valeria-vol pull request #8
Opened 2023-06-25 10:45 UTC by valeriarykova

2023-06-25 10:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-25 19:46 UTC, GSemikozov requested changes

2023-06-25 19:46 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px 40px 28px;
`28 26 32`

2023-06-25 19:46 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  padding-bottom: 24px;
margin-bottom

2023-07-12 10:10 UTC, valeriarykova commented on 05-lection3/03-calendar/calendar.css
> +  padding: 28px 30px 40px 28px;
поправила

2023-07-12 10:10 UTC, valeriarykova commented on 05-lection3/03-calendar/calendar.css
> +  padding-bottom: 24px;
поправила

2023-07-12 14:02 UTC, GSemikozov approved these changes

2023-07-12 14:02 UTC, merged